version: 2.1


jobs:
  build-and-test:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:5.0
    steps:
      - checkout
      - run: dotnet restore
      - run: dotnet build
      - run: dotnet run

  commitlint:
    docker:
      - image: williamlauze/circleci-commitlint:latest
    working_directory: /www
    steps:
      - checkout
      - run:
          name: Lint commit messages
          command: |
            /bin/sh /.scripts/commitlint_range.sh
workflows:
  sample: 
    jobs:
      - build-and-test
      - commitlint
